Fix openmuc pid and log file locations

diff --git a/packages/openmuc-core/bin/openmuc b/packages/openmuc-core/bin/openmuc
--- a/packages/openmuc-core/bin/openmuc
+++ b/packages/openmuc-core/bin/openmuc
@@ -7,12 +7,33 @@ OPENMUC_HOME="/opt/openmuc"
 JVM_OPTS=""
 
 # Set location for PID and Error output file. Default is "$EMONMUC_DIR/log/openmuc.pid" or ".log"
-PID_FILE=/var/run/emonmuc/openmuc.pid
-#ERR_FILE=/var/log/emonmuc/openmuc.out
+PID_FILE=/var/run/openmuc/openmuc.pid
+#ERR_FILE=/var/log/openmuc/openmuc.out
 ERR_FILE=/dev/null
 
 cd "$OPENMUC_HOME"
 
+# Determine the Java command to use to start the JVM.
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+        JAVACMD="$JAVA_HOME/bin/java"
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
+else
+    JAVACMD="java"
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+fi
 
 # Apache Felix FileInstall
 # Since FileInstall doesn't create the felix.fileinstall.dir by itself, this script creates
